# Generated by Django 4.2.3 on 2023-11-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Address', models.CharField(blank=True, max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('EIN', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Othertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.organization')),
            ],
        ),
    ]
